config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
            #controller#method
  root to: 'katas#index'
  #                                      #kata_path
  # get 'kata/:id' => 'katas#show', as: :kata
  #
  # get 'edit/:id' => 'katas#edit', as: :edit_kata
  #
  # patch 'kata/:id' => 'katas#update'
  #
  # delete 'kata/:id' => 'katas#delete', as: :delete_kata
  #
  # get 'new/kata' => 'katas#new', as: :new_kata
  #
  # post 'create/kata' => 'katas#create', as: :create_kata

  resources :katas
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/belt.rb
class Belt < ApplicationRecord
  belongs_to :kata

  def self.find_kata_id(id)
      belt = self.find(id)
      belt.kata.id
  end

  def self.full_kata(id)
    belt = self.find(id)
    "#{belt.name} #{belt.description}"
  end

  def inline
    "#{name} #{description}"
  end
end

app/models/kata.rb
class Kata < ApplicationRecord
  validates :title, :description, presence: true
  has_many :belts
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/katas_controller.rb
class KatasController < ApplicationController

  before_action :set_kata, only: [:edit, :update, :destroy, :show ]
  before_action :authenticate_user!, only: [:edit, :update, :destroy, :new, :create]

  def index
    @katas = Kata.all
  end

  def edit
    render :edit
  end

  def update
    if @kata.update(kata_params)
      flash[:notice] = 'Kata updated!'
      redirect_to root_path
    else
      flash[:error] = 'Failed to edit kata!'
      render :edit
    end
  end

  def destroy
    @kata.destroy
    redirect_to root_path
  end

  def show
    render :show
  end

  def new
    @kata = Kata.new
  end

  def create
    @kata = Kata.new(kata_params)
    if @kata.save
      flash[:notice] = 'Kata created!'
      redirect_to kata_path(@kata.id)
    else
      flash[:error] = 'Failed to create kata!'
      render :new
    end
  end

  private

  def kata_params
    params.require(:kata).permit(:title, :description) #.permit(:name, :price, :old_price, :short_description, :full_description)
  end

  def set_kata
    @kata = Kata.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/katas_helper.rb
module KatasHelper
  NO_LINK = ''
  def destroy_kata_link(id)
    return link_to('Delete', kata_path(id), { method: :delete, data: { confirm: 'Are you sure?' }}) if user_signed_in?
    NO_LINK
  end
end

app/views/katas/_form.html.erb
<div>
  <p>
    <% if @kata.errors %>
    <ul>
      <% @kata.errors.each do | error | %>
      <li><%= error %></li>
      <% end %>
    </ul>
    <% end %>
  </p>
</div>
<%= form_for(@kata) do |field| %>
<p><%= field.text_field :title %></p>
<p><%= field.text_field :description %></p>
<p><%= field.submit t(:save) %></p>
<% end %>

app/views/katas/edit.html.erb
<h1><%= t("edit.title", name: 'Nacho') %></h1>

<%= render 'form', note: @kata %>

app/views/katas/index.html.erb
<h1>Katas</h1>
<h4> <%= link_to('Log out', destroy_user_session_path, { method: :delete}) %></h4>
<p><%= link_to('New kata', new_kata_path) %></p>
<ul>
<% @katas.each do |kata| %>
  <li>
    <%= link_to(kata.title, kata_path(kata.id)) %>
    <%= link_to('Edit', edit_kata_path(kata.id)) if user_signed_in? %>
    <%= destroy_kata_link(kata.id) %>
  </li>
<% end %>
</ul>

app/views/katas/new.html.erb
<h1>Create katas</h1>

<%= render 'form', note: @kata %>

app/views/katas/show.html.erb
<h2><%= @kata.title %></h2>
<p><%= @kata.description %></p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Myapp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% I18n.locale = :es %>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>